"""
pdf_report.py
=============
Phase 3 — Styled PDF Architectural Report Generator (ReportLab Platypus).

Generates a 4-page PDF:
  Page 1: Cover — project metadata
  Page 2: Floor Plan image (base64 PNG from the layout)
  Page 3: Vastu Analysis table
  Page 4: Bill of Materials table with grand total

Returns raw PDF bytes suitable for a FastAPI Response download.
"""

from __future__ import annotations

import base64
import io
from datetime import date
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate,
    Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, HRFlowable, PageBreak,
)

# ── Brand colours ──────────────────────────────────────────────────────────────
BRAND_DARK   = colors.HexColor("#0f172a")
BRAND_ACCENT = colors.HexColor("#22c55e")
BRAND_MID    = colors.HexColor("#334155")
BRAND_LIGHT  = colors.HexColor("#f8fafc")
PASS_GREEN   = colors.HexColor("#16a34a")
WARN_AMBER   = colors.HexColor("#d97706")
FAIL_RED     = colors.HexColor("#dc2626")
HEADER_BG    = colors.HexColor("#1e293b")
ROW_ALT      = colors.HexColor("#f1f5f9")


# ── Helper: INR formatting ────────────────────────────────────────────────────

def _inr(amount: float) -> str:
    """Format a float as Indian Rupee string with lakh/crore grouping."""
    if amount >= 1_00_00_000:
        return f"₹{amount / 1_00_00_000:.2f} Cr"
    if amount >= 1_00_000:
        return f"₹{amount / 1_00_000:.2f} L"
    return f"₹{amount:,.0f}"


# ── Helper: page header/footer ─────────────────────────────────────────────────

def _draw_header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4

    # Header strip
    canvas.setFillColor(HEADER_BG)
    canvas.rect(0, h - 1.4 * cm, w, 1.4 * cm, fill=1, stroke=0)
    canvas.setFillColor(BRAND_ACCENT)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(1.5 * cm, h - 0.9 * cm, "⬡  AI ARCHITECT")
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(w - 1.5 * cm, h - 0.9 * cm, "ARCHITECTURAL REPORT")

    # Footer line
    canvas.setStrokeColor(BRAND_MID)
    canvas.setLineWidth(0.5)
    canvas.line(1.5 * cm, 1.2 * cm, w - 1.5 * cm, 1.2 * cm)
    canvas.setFillColor(BRAND_MID)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(1.5 * cm, 0.7 * cm, "Generated by AI Architect · For illustrative purposes only")
    canvas.drawRightString(w - 1.5 * cm, 0.7 * cm, f"Page {doc.page}")

    canvas.restoreState()


# ── Styles ─────────────────────────────────────────────────────────────────────

def _build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("h1", parent=base["Title"],
                             fontSize=28, textColor=BRAND_DARK,
                             spaceAfter=6, fontName="Helvetica-Bold", alignment=TA_CENTER),
        "h2": ParagraphStyle("h2", parent=base["Heading2"],
                             fontSize=16, textColor=BRAND_ACCENT,
                             spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold"),
        "body": ParagraphStyle("body", parent=base["Normal"],
                               fontSize=9, textColor=BRAND_MID,
                               spaceAfter=4, fontName="Helvetica"),
        "meta": ParagraphStyle("meta", parent=base["Normal"],
                               fontSize=10, textColor=BRAND_DARK,
                               spaceAfter=6, fontName="Helvetica"),
        "small": ParagraphStyle("small", parent=base["Normal"],
                                fontSize=7.5, textColor=BRAND_MID,
                                fontName="Helvetica", alignment=TA_CENTER),
        "center": ParagraphStyle("center", parent=base["Normal"],
                                 fontSize=9, textColor=BRAND_MID,
                                 fontName="Helvetica", alignment=TA_CENTER),
    }


# ── Table style helpers ────────────────────────────────────────────────────────

def _std_table_style(num_rows: int) -> TableStyle:
    """Alternating-row striped table style."""
    cmds = [
        ("BACKGROUND",  (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, 0), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [BRAND_LIGHT, ROW_ALT]),
        ("FONTNAME",    (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 1), (-1, -1), 8),
        ("ALIGN",       (0, 0), (-1, -1), "LEFT"),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("GRID",        (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
        ("LINEBELOW",   (0, 0), (-1, 0), 1.0, BRAND_ACCENT),
    ]
    # Bold last row (totals)
    if num_rows > 1:
        cmds += [
            ("BACKGROUND", (0, -1), (-1, -1), HEADER_BG),
            ("TEXTCOLOR",  (0, -1), (-1, -1), colors.white),
            ("FONTNAME",   (0, -1), (-1, -1), "Helvetica-Bold"),
        ]
    return TableStyle(cmds)


# ── Public API ────────────────────────────────────────────────────────────────

def generate_report_pdf(
    layout: dict,
    vastu_result: dict,
    bom: dict,
    project_meta: dict,
) -> bytes:
    """
    Generate a complete styled PDF report.

    Args:
        layout:       Full layout dict (from build_layout_from_topology).
        vastu_result: Dict with keys: score, grade, rules.
        bom:          Dict from compute_bom — {rooms: [...], summary: {...}}.
        project_meta: {
            "name":      str,   e.g. "3BHK East-facing 40×30ft"
            "length":    float, "width": float,
            "bedrooms":  int,   "bathrooms": int,
            "entry_dir": str,   "vastu": bool,
        }

    Returns:
        Raw PDF bytes.
    """
    buf = io.BytesIO()
    styles = _build_styles()

    w, h = A4
    margin = 1.5 * cm
    doc = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=margin, rightMargin=margin,
        topMargin=1.8 * cm, bottomMargin=1.8 * cm,
    )
    frame = Frame(margin, margin, w - 2 * margin, h - 2 * margin, id="main")
    template = PageTemplate(id="main", frames=[frame], onPage=_draw_header_footer)
    doc.addPageTemplates([template])

    story: list[Any] = []

    # ── Page 1: Cover ─────────────────────────────────────────────────────────
    story.append(Spacer(1, 2 * cm))
    story.append(Paragraph("ARCHITECTURAL REPORT", styles["h1"]))
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND_ACCENT, spaceAfter=12))
    story.append(Spacer(1, 0.5 * cm))

    name = project_meta.get("name", "Generated Floor Plan")
    story.append(Paragraph(name, ParagraphStyle(
        "proj_name", fontSize=18, fontName="Helvetica-Bold",
        textColor=BRAND_DARK, alignment=TA_CENTER, spaceAfter=10,
    )))

    entry_dir_str = str(project_meta.get("entry_dir") or "N/A").capitalize()
    meta_data = [
        ["Plot Size",     f"{project_meta.get('length', 0)} × {project_meta.get('width', 0)} ft"],
        ["Bedrooms",      str(project_meta.get("bedrooms", 0))],
        ["Bathrooms",     str(project_meta.get("bathrooms", 0))],
        ["Entry Facing",  entry_dir_str],
        ["Vastu Enabled", "Yes" if project_meta.get("vastu") else "No"],
        ["Vastu Score",   f"{vastu_result.get('score', 0)}/100 ({vastu_result.get('grade', '')})"],
        ["Report Date",   date.today().strftime("%d %B %Y")],
    ]
    meta_table = Table(meta_data, colWidths=[5 * cm, 10 * cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME",   (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",   (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",   (0, 0), (-1, -1), 10),
        ("TEXTCOLOR",  (0, 0), (0, -1), BRAND_DARK),
        ("TEXTCOLOR",  (1, 0), (1, -1), BRAND_MID),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("LINEBELOW",  (0, 0), (-1, -2), 0.3, colors.HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [BRAND_LIGHT, ROW_ALT]),
    ]))
    story.append(meta_table)
    story.append(PageBreak())

    # ── Page 2: Floor Plan Image ───────────────────────────────────────────────
    story.append(Paragraph("Floor Plan", styles["h2"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_ACCENT, spaceAfter=8))

    floors = layout.get("floors", [])
    if not floors:
        img_url = layout.get("imageUrl", "")
        rooms_list = layout.get("rooms", [])
        if img_url or rooms_list:
            floors = [{"level": "Ground Floor", "rooms": rooms_list, "imageUrl": img_url}]

    for floor in floors:
        img_b64 = floor.get("imageUrl") or layout.get("imageUrl", "")
        if img_b64 and img_b64.startswith("data:image/png;base64,"):
            img_bytes = base64.b64decode(img_b64.split(",", 1)[1])
            img_buf = io.BytesIO(img_bytes)
            rl_img = RLImage(img_buf, width=w - 4 * cm, height=(w - 4 * cm) * 0.75)
            story.append(Paragraph(floor.get("level", "Floor"), styles["meta"]))
            story.append(rl_img)
            story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph(
        "Floor plan generated by AI Architect. All dimensions are in feet. "
        "Verify with a licensed architect before construction.",
        styles["small"],
    ))
    story.append(PageBreak())

    # ── Page 3: Vastu Analysis ─────────────────────────────────────────────────
    story.append(Paragraph("Vastu Shastra Analysis", styles["h2"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_ACCENT, spaceAfter=8))

    score = vastu_result.get("score", 0)
    grade = vastu_result.get("grade", "N/A")
    story.append(Paragraph(f"Overall Score: <b>{score}/100</b> — Grade: <b>{grade}</b>", styles["meta"]))
    story.append(Spacer(1, 0.3 * cm))

    vastu_rules = vastu_result.get("rules", [])
    if vastu_rules:
        vastu_rows = [["Rule", "Status", "Points", "Detail"]]
        for r in vastu_rules:
            if r.get("max", 0) == 0:
                continue
            status = r.get("status", "")
            icon   = "✅ Pass" if status == "pass" else ("⚠ Warn" if status == "warn" else "❌ Fail")
            vastu_rows.append([
                Paragraph(str(r.get("rule", "")), styles["body"]),
                icon,
                f"{r.get('points', 0)}/{r.get('max', 0)}",
                Paragraph(str(r.get("detail", "")), styles["body"]),
            ])

        col_w = [4.5 * cm, 2 * cm, 2 * cm, 9 * cm]
        vastu_table = Table(vastu_rows, colWidths=col_w, repeatRows=1)
        vastu_table.setStyle(_std_table_style(len(vastu_rows)))
        # Colour the status column by value
        for row_idx, r in enumerate(vastu_rows[1:], start=1):
            status_cell = r[1]
            clr = PASS_GREEN if "Pass" in status_cell else (WARN_AMBER if "Warn" in status_cell else FAIL_RED)
            vastu_table.setStyle(TableStyle([("TEXTCOLOR", (1, row_idx), (1, row_idx), clr)]))
        story.append(vastu_table)

    story.append(PageBreak())

    # ── Page 4: Bill of Materials ──────────────────────────────────────────────
    story.append(Paragraph("Bill of Materials — Cost Estimate (INR)", styles["h2"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_ACCENT, spaceAfter=8))

    summary = bom.get("summary", {})
    story.append(Paragraph(
        f"Total Area: <b>{summary.get('total_area_sqft', 0):.0f} sqft</b> · "
        f"Est. Rate: <b>{_inr(summary.get('rate_per_sqft', 0))}/sqft</b>",
        styles["meta"],
    ))
    story.append(Spacer(1, 0.3 * cm))

    bom_rows = [["Room", "Area\n(sqft)", "Doors/\nWindows", "Material\nCost", "Labour\nCost", "Total"]]
    for r in bom.get("rooms", []):
        costs = r.get("costs", {})
        bom_rows.append([
            r.get("name", ""),
            f"{r.get('area_sqft', 0):.0f}",
            f"{r.get('num_doors', 0)}D / {r.get('num_windows', 0)}W",
            _inr(costs.get("material", 0)),
            _inr(costs.get("labour", 0)),
            _inr(costs.get("total", 0)),
        ])

    # Grand total row
    bom_rows.append([
        "GRAND TOTAL", f"{summary.get('total_area_sqft', 0):.0f}", "",
        _inr(summary.get("material_total", 0)),
        _inr(summary.get("labour_total", 0)),
        _inr(summary.get("grand_total", 0)),
    ])

    col_w = [4.5 * cm, 1.5 * cm, 2 * cm, 3 * cm, 2.5 * cm, 3 * cm]
    bom_table = Table(bom_rows, colWidths=col_w, repeatRows=1)
    bom_table.setStyle(_std_table_style(len(bom_rows)))
    story.append(bom_table)

    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(
        "⚠ Disclaimer: All cost figures are indicative estimates based on 2026 Indian market rates. "
        "Actual costs depend on location, material quality, and contractor rates. "
        "Always obtain a formal Bill of Quantities (BOQ) from a licensed architect or contractor.",
        styles["small"],
    ))

    # ── Build PDF ──────────────────────────────────────────────────────────────
    doc.build(story)
    buf.seek(0)
    return buf.read()
