"""
pdf_report.py
=============
Premium Light-Mode Architectural Report Generator (ReportLab Platypus).

Generates a multi-page PDF with:
  Page 1: Cover — hero project metadata
  Page 2: Executive Summary (area, rooms, scores at a glance)
  Page 3: Floor Plan image(s) per floor
  Page 4: Vastu Shastra Analysis
  Page 5: NBC Compliance
  Page 6: Energy Efficiency
  Page 7: Sunlight Analysis
  Page 8: Bill of Materials & Cost Estimate

Light mode: white background, dark ink — professional print-ready.
Returns raw PDF bytes suitable for a FastAPI Response download.
"""

from __future__ import annotations

import base64
import io
from datetime import date
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate,
    Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, HRFlowable, PageBreak,
)

# ── Light Mode Brand Palette ──────────────────────────────────────────────────
BRAND_INK      = colors.HexColor("#0f172a")   # Near-black text
BRAND_ACCENT   = colors.HexColor("#16a34a")   # AI Architect green
BRAND_ACCENT2  = colors.HexColor("#0369a1")   # Blue for info sections
BRAND_WARN     = colors.HexColor("#d97706")   # Amber for warnings
BRAND_FAIL     = colors.HexColor("#dc2626")   # Red for failures
BRAND_MID      = colors.HexColor("#475569")   # Slate-600 body text
BRAND_LIGHT    = colors.HexColor("#f8fafc")   # Near-white row alt
BRAND_BORDER   = colors.HexColor("#e2e8f0")   # Table borders
BRAND_HEADER   = colors.HexColor("#1e293b")   # Header stripe (dark)
ROW_ALT        = colors.HexColor("#f1f5f9")   # Light grey row alt
SECTION_TEAL   = colors.HexColor("#0d9488")   # Teal for energy
SECTION_SUN    = colors.HexColor("#b45309")   # Amber-brown for sunlight
SECTION_NBC    = colors.HexColor("#7c3aed")   # Purple for NBC


# ── INR formatter ─────────────────────────────────────────────────────────────
def _inr(amount: float) -> str:
    if amount >= 1_00_00_000:
        return f"Rs. {amount / 1_00_00_000:.2f} Cr"
    if amount >= 1_00_000:
        return f"Rs. {amount / 1_00_000:.2f} L"
    return f"Rs. {amount:,.0f}"


# ── Page canvas callback — draws the header/footer on every page ──────────────
def _draw_header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4

    # Top bar — white background, thin accent bottom border, logo on left
    canvas.setFillColor(colors.white)
    canvas.rect(0, h - 1.2 * cm, w, 1.2 * cm, fill=1, stroke=0)
    canvas.setStrokeColor(BRAND_ACCENT)
    canvas.setLineWidth(2)
    canvas.line(0, h - 1.2 * cm, w, h - 1.2 * cm)

    # Logo text
    canvas.setFillColor(BRAND_ACCENT)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(1.5 * cm, h - 0.82 * cm, "⬡ AI ARCHITECT")
    canvas.setFillColor(BRAND_MID)
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(w - 1.5 * cm, h - 0.82 * cm, "ARCHITECTURAL PROJECT DOSSIER")

    # Footer — thin top line
    canvas.setStrokeColor(BRAND_BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(1.5 * cm, 1.0 * cm, w - 1.5 * cm, 1.0 * cm)
    canvas.setFillColor(BRAND_MID)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(1.5 * cm, 0.5 * cm, "Generated by AI Architect · For illustrative purposes only · Verify with a licensed architect before construction")
    canvas.drawRightString(w - 1.5 * cm, 0.5 * cm, f"Page {doc.page}")

    canvas.restoreState()


# ── Build style library ────────────────────────────────────────────────────────
def _build_styles() -> dict[str, ParagraphStyle]:
    return {
        "cover_title": ParagraphStyle("cover_title",
            fontSize=32, fontName="Helvetica-Bold",
            textColor=BRAND_INK, alignment=TA_CENTER, spaceAfter=8, leading=38),
        "cover_sub": ParagraphStyle("cover_sub",
            fontSize=14, fontName="Helvetica",
            textColor=BRAND_MID, alignment=TA_CENTER, spaceAfter=4),
        "section_title": ParagraphStyle("section_title",
            fontSize=14, fontName="Helvetica-Bold",
            textColor=BRAND_INK, spaceBefore=16, spaceAfter=6),
        "section_accent": ParagraphStyle("section_accent",
            fontSize=14, fontName="Helvetica-Bold",
            textColor=BRAND_ACCENT, spaceBefore=16, spaceAfter=6),
        "section_blue": ParagraphStyle("section_blue",
            fontSize=14, fontName="Helvetica-Bold",
            textColor=BRAND_ACCENT2, spaceBefore=16, spaceAfter=6),
        "section_purple": ParagraphStyle("section_purple",
            fontSize=14, fontName="Helvetica-Bold",
            textColor=SECTION_NBC, spaceBefore=16, spaceAfter=6),
        "section_teal": ParagraphStyle("section_teal",
            fontSize=14, fontName="Helvetica-Bold",
            textColor=SECTION_TEAL, spaceBefore=16, spaceAfter=6),
        "section_sun": ParagraphStyle("section_sun",
            fontSize=14, fontName="Helvetica-Bold",
            textColor=SECTION_SUN, spaceBefore=16, spaceAfter=6),
        "body": ParagraphStyle("body",
            fontSize=9, fontName="Helvetica",
            textColor=BRAND_MID, spaceAfter=4, leading=13),
        "body_bold": ParagraphStyle("body_bold",
            fontSize=9, fontName="Helvetica-Bold",
            textColor=BRAND_INK, spaceAfter=4),
        "meta": ParagraphStyle("meta",
            fontSize=10, fontName="Helvetica",
            textColor=BRAND_INK, spaceAfter=5),
        "kpi_label": ParagraphStyle("kpi_label",
            fontSize=8, fontName="Helvetica",
            textColor=BRAND_MID, alignment=TA_CENTER),
        "kpi_value": ParagraphStyle("kpi_value",
            fontSize=22, fontName="Helvetica-Bold",
            textColor=BRAND_INK, alignment=TA_CENTER, spaceAfter=2),
        "small": ParagraphStyle("small",
            fontSize=7.5, fontName="Helvetica",
            textColor=BRAND_MID, alignment=TA_CENTER),
        "insight": ParagraphStyle("insight",
            fontSize=9, fontName="Helvetica",
            textColor=BRAND_MID, leftIndent=10, spaceAfter=3, leading=13),
        "disclaimer": ParagraphStyle("disclaimer",
            fontSize=8, fontName="Helvetica",
            textColor=BRAND_MID, alignment=TA_CENTER, spaceBefore=12),
    }


# ── Standard striped table style ──────────────────────────────────────────────
def _std_table(num_rows: int, accent_color=None) -> TableStyle:
    acc = accent_color or BRAND_ACCENT
    cmds = [
        ("BACKGROUND",    (0, 0), (-1, 0),  BRAND_HEADER),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  colors.white),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0),  8),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, ROW_ALT]),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, -1), 8),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN",         (0, 0), (-1, -1), "LEFT"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("GRID",          (0, 0), (-1, -1), 0.35, BRAND_BORDER),
        ("LINEBELOW",     (0, 0), (-1, 0),  1.2,  acc),
        ("ROUNDEDCORNERS",(0, 0), (-1, -1), 2),
    ]
    if num_rows > 1:
        cmds += [
            ("BACKGROUND", (0, -1), (-1, -1), BRAND_HEADER),
            ("TEXTCOLOR",  (0, -1), (-1, -1), colors.white),
            ("FONTNAME",   (0, -1), (-1, -1), "Helvetica-Bold"),
        ]
    return TableStyle(cmds) # type: ignore


# ── Section divider helper ─────────────────────────────────────────────────────
def _section(story, title, style_key, styles, accent=None):
    acc = accent or BRAND_ACCENT
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(title, styles[style_key]))
    story.append(HRFlowable(width="100%", thickness=1.5, color=acc, spaceAfter=8))


# ── Score badge helper (returns colored Paragraph) ────────────────────────────
def _score_badge(score: int, grade: str, styles) -> Paragraph:
    if score >= 70:
        clr = "#16a34a"
    elif score >= 45:
        clr = "#d97706"
    else:
        clr = "#dc2626"
    return Paragraph(
        f'<font color="{clr}"><b>{score}/100 — {grade}</b></font>',
        styles["meta"]
    )


# ── Status cell with colour ───────────────────────────────────────────────────
def _status_cell(status: str) -> str:
    if status == "pass":   return "(Pass)"
    if status == "warn":   return "(Warn)"
    return "(Fail)"


def _status_color(status: str):
    if status == "pass":   return BRAND_ACCENT
    if status == "warn":   return BRAND_WARN
    return BRAND_FAIL


def _safe(text: str) -> str:
    """Strip emoji that confuse ReportLab Helvetica."""
    emoji = ["✅", "❌", "⚠️", "⚠", "🌟", "✨", "🏠", "🌿", "🌞"]
    for e in emoji:
        text = text.replace(e, "")
    return text.strip()


# ── Public API ────────────────────────────────────────────────────────────────
def generate_report_pdf(
    layout: dict,
    vastu_result: dict,
    bom: dict,
    project_meta: dict,
) -> bytes:
    """
    Generate a comprehensive, premium light-mode PDF report.

    Args:
        layout:        Full layout dict (floors, energyResult, sunlightResult, etc.)
        vastu_result:  Dict with score, grade, rules.
        bom:           Dict from compute_bom — {rooms: [...], summary: {...}}.
        project_meta:  {name, length, width, bedrooms, bathrooms, entry_dir, vastu}

    Returns:
        Raw PDF bytes.
    """
    buf = io.BytesIO()
    styles = _build_styles()
    w, h = A4
    margin = 1.5 * cm

    doc = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=margin, rightMargin=margin,
        topMargin=1.8 * cm, bottomMargin=1.6 * cm,
    )
    frame = Frame(margin, margin, w - 2 * margin, h - 2 * margin, id="main")
    template = PageTemplate(id="main", frames=[frame], onPage=_draw_header_footer)
    doc.addPageTemplates([template])

    story: list[Any] = []

    # ── Extract nested results from layout dict ───────────────────────────────
    nbc_result     = layout.get("nbcResult")     or layout.get("nbc_result")     or {}
    energy_result  = layout.get("energyResult")  or layout.get("energy_result")  or {}
    sunlight_result= layout.get("sunlightResult")or layout.get("sunlight_result")or {}
    floors         = layout.get("floors", [])
    if not floors:
        rooms_list = layout.get("rooms", [])
        floors = [{"level": "Ground Floor", "rooms": rooms_list, "imageUrl": layout.get("imageUrl", "")}]

    name       = project_meta.get("name", "AI-Generated Floor Plan")
    plot_l     = project_meta.get("length", 0)
    plot_w     = project_meta.get("width", 0)
    bedrooms   = project_meta.get("bedrooms", 0)
    bathrooms  = project_meta.get("bathrooms", 0)
    entry_dir  = str(project_meta.get("entry_dir") or "N/A").capitalize()
    today      = date.today().strftime("%d %B %Y")

    vastu_score  = vastu_result.get("score", 0)
    vastu_grade  = vastu_result.get("grade", "N/A")
    nbc_score    = nbc_result.get("score", 0)
    nbc_grade    = nbc_result.get("grade", "N/A")
    energy_score = energy_result.get("score", 0)
    energy_grade = energy_result.get("grade", "N/A")
    sun_score    = sunlight_result.get("score", 0)
    sun_grade    = sunlight_result.get("grade", "N/A")
    total_rooms  = sum(len(f.get("rooms", [])) for f in floors)
    summary      = bom.get("summary", {})
    total_area   = summary.get("total_area_sqft", round(plot_l * plot_w))
    grand_total  = summary.get("grand_total", 0)

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 1: COVER
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(Spacer(1, 1.5 * cm))

    # Green accent line at top of content
    story.append(HRFlowable(width="100%", thickness=4, color=BRAND_ACCENT, spaceAfter=20))

    story.append(Paragraph("ARCHITECTURAL PROJECT DOSSIER", styles["cover_sub"]))
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph(name, styles["cover_title"]))
    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="40%", thickness=1.5, color=BRAND_BORDER, spaceAfter=16))

    # Cover meta table
    cover_data = [
        ["Plot Dimensions",  f"{plot_l} × {plot_w} ft  ({total_area:,.0f} sq ft)"],
        ["Configuration",    f"{bedrooms} Bedrooms · {bathrooms} Bathrooms"],
        ["Entry Facing",     entry_dir],
        ["Total Rooms",      str(total_rooms)],
        ["Vastu Enabled",    "Yes" if project_meta.get("vastu") else "No"],
        ["Report Date",      today],
    ]
    cov_table = Table(cover_data, colWidths=[5.5 * cm, 10.5 * cm])
    cov_table.setStyle(TableStyle([
        ("FONTNAME",      (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",      (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 0), (-1, -1), 10),
        ("TEXTCOLOR",     (0, 0), (0, -1), BRAND_INK),
        ("TEXTCOLOR",     (1, 0), (1, -1), BRAND_MID),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("LINEBELOW",     (0, 0), (-1, -2), 0.3, BRAND_BORDER),
        ("ROWBACKGROUNDS",(0, 0), (-1, -1), [colors.white, BRAND_LIGHT]),
    ]))
    story.append(cov_table)

    story.append(Spacer(1, 0.8 * cm))
    story.append(Paragraph(
        "This report is a comprehensive analysis of your AI-generated architectural design, "
        "including floor plan layouts, Vastu Shastra compliance, NBC structural codes, "
        "energy efficiency, sunlight analysis, and detailed cost estimates.",
        styles["body"]
    ))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 2: EXECUTIVE SUMMARY — KPI cards
    # ═══════════════════════════════════════════════════════════════════════════
    _section(story, "Executive Summary", "section_accent", styles, BRAND_ACCENT)

    # 4 KPI cards in a row
    def _kpi(label, value, unit=""):
        return [
            Paragraph(label, styles["kpi_label"]),
            Paragraph(f"{value}", styles["kpi_value"]),
            Paragraph(unit, styles["kpi_label"]),
        ]

    kpi_data = [[
        _kpi("Total Area", f"{total_area:,.0f}", "sq ft"),
        _kpi("Rooms", total_rooms, "total"),
        _kpi("Est. Cost", _inr(grand_total), "incl. labour"),
        _kpi("Vastu Score", vastu_score, f"/ 100 · {vastu_grade}"),
    ]]

    kpi_table = Table(kpi_data, colWidths=[4.1 * cm] * 4)
    kpi_table.setStyle(TableStyle([
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING",    (0, 0), (-1, -1), 12),
        ("BOX",           (0, 0), (0, 0),   1, BRAND_BORDER),
        ("BOX",           (1, 0), (1, 0),   1, BRAND_BORDER),
        ("BOX",           (2, 0), (2, 0),   1, BRAND_BORDER),
        ("BOX",           (3, 0), (3, 0),   1, BRAND_BORDER),
        ("LEFTPADDING",   (0, 0), (-1, -1), 4),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 4),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 0.5 * cm))

    # Score overview table
    score_data = [
        ["Analysis Module", "Score", "Grade", "Status"],
        ["Vastu Shastra",    f"{vastu_score}/100",  vastu_grade,
            "(Pass)" if vastu_score >= 60 else ("(Warn)" if vastu_score >= 40 else "(Fail)")],
        ["NBC Compliance",   f"{nbc_score}/100",    nbc_grade,
            "(Pass)" if nbc_score >= 60 else ("(Warn)" if nbc_score >= 40 else "(Fail)")],
        ["Energy Efficiency",f"{energy_score}/100", energy_grade,
            "(Pass)" if energy_score >= 60 else ("(Warn)" if energy_score >= 40 else "(Fail)")],
        ["Sunlight Analysis",f"{sun_score}/100",    sun_grade,
            "(Pass)" if sun_score >= 60 else ("(Warn)" if sun_score >= 40 else "(Fail)")],
    ]
    score_table = Table(score_data, colWidths=[6.5 * cm, 2.5 * cm, 3 * cm, 4 * cm])
    score_table.setStyle(_std_table(len(score_data)))
    # Colour the status column
    for i, row in enumerate(score_data[1:], 1):
        st = row[3]
        clr = BRAND_ACCENT if "Pass" in st else (BRAND_WARN if "Warn" in st else BRAND_FAIL)
        score_table.setStyle(TableStyle([("TEXTCOLOR", (3, i), (3, i), clr)]))
    story.append(score_table)

    # Floor breakdown
    story.append(Spacer(1, 0.5 * cm))
    _section(story, "Floor Summary", "section_title", styles)
    fl_data = [["Floor", "Room Count", "Room Names"]]
    for floor in floors:
        rms = floor.get("rooms", [])
        room_names = ", ".join(r.get("name", "?") for r in rms[:8])
        if len(rms) > 8:
            room_names += f" + {len(rms)-8} more"
        fl_data.append([floor.get("level", "Floor"), str(len(rms)), room_names])
    fl_table = Table(fl_data, colWidths=[4.5 * cm, 2.5 * cm, 9 * cm])
    fl_table.setStyle(_std_table(len(fl_data)))
    story.append(fl_table)

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 3: FLOOR PLAN IMAGES
    # ═══════════════════════════════════════════════════════════════════════════
    _section(story, "Floor Plan Layouts", "section_accent", styles, BRAND_ACCENT)
    story.append(Paragraph(
        "High-resolution floor plan generated by the AI Architect engine. "
        "All dimensions are in feet. Scale: 1 unit = 1 ft.",
        styles["body"]
    ))
    story.append(Spacer(1, 0.3 * cm))

    img_added = False
    for floor in floors:
        img_b64 = floor.get("imageUrl") or layout.get("imageUrl", "")
        if img_b64 and img_b64.startswith("data:image/png;base64,"):
            img_bytes = base64.b64decode(img_b64.split(",", 1)[1])
            img_buf = io.BytesIO(img_bytes)
            try:
                from PIL import Image as PILImage
                with PILImage.open(img_buf) as pimg:
                    pw, ph = pimg.size
                    ratio = ph / pw
            except Exception:
                ratio = 0.75
            img_buf.seek(0)
            avail_w = w - 4 * cm
            rl_img = RLImage(img_buf, width=avail_w, height=avail_w * ratio)
            story.append(Paragraph(f"<b>{floor.get('level', 'Floor')}</b>", styles["meta"]))
            story.append(rl_img)
            story.append(Spacer(1, 0.4 * cm))
            img_added = True

    if not img_added:
        story.append(Paragraph("No floor plan image available.", styles["body"]))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 4: VASTU SHASTRA ANALYSIS
    # ═══════════════════════════════════════════════════════════════════════════
    _section(story, "Vastu Shastra Analysis", "section_accent", styles, BRAND_ACCENT)
    story.append(_score_badge(vastu_score, vastu_grade, styles))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        "Vastu Shastra is the traditional Hindu system of architecture that aligns spaces "
        "with natural energies. A score above 60 indicates good Vastu compliance.",
        styles["body"]
    ))
    story.append(Spacer(1, 0.3 * cm))

    vastu_rules = vastu_result.get("rules", [])
    if vastu_rules:
        vrows = [["Rule", "Status", "Pts", "Detail"]]
        for r in vastu_rules:
            if r.get("max", 0) == 0:
                continue
            vrows.append([
                Paragraph(_safe(str(r.get("rule", ""))), styles["body"]), # type: ignore
                _status_cell(r.get("status", "")),
                f"{r.get('points', 0)}/{r.get('max', 0)}",
                Paragraph(_safe(str(r.get("detail", ""))), styles["body"]), # type: ignore
            ])
        col_w = [4.5 * cm, 1.8 * cm, 1.6 * cm, 8.1 * cm]
        vtable = Table(vrows, colWidths=col_w, repeatRows=1)
        vtable.setStyle(_std_table(len(vrows), BRAND_ACCENT))
        for ri, r in enumerate(vastu_rules, 1):
            if ri >= len(vrows):
                break
            clr = _status_color(r.get("status", "fail"))
            vtable.setStyle(TableStyle([("TEXTCOLOR", (1, ri), (1, ri), clr)]))
        story.append(vtable)
    else:
        story.append(Paragraph("No Vastu data available.", styles["body"]))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 5: NBC COMPLIANCE
    # ═══════════════════════════════════════════════════════════════════════════
    _section(story, "NBC Compliance (National Building Code)", "section_purple", styles, SECTION_NBC)
    story.append(_score_badge(nbc_score, nbc_grade, styles))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        "The National Building Code of India sets minimum standards for construction safety, "
        "room dimensions, ventilation, and structural requirements.",
        styles["body"]
    ))
    story.append(Spacer(1, 0.3 * cm))

    nbc_rules = nbc_result.get("rules", [])
    if nbc_rules:
        nrows = [["Rule", "Status", "Pts", "Detail"]]
        for r in nbc_rules:
            if r.get("max", 0) == 0:
                continue
            nrows.append([
                Paragraph(_safe(str(r.get("rule", ""))), styles["body"]), # type: ignore
                _status_cell(r.get("status", "")),
                f"{r.get('points', 0)}/{r.get('max', 0)}",
                Paragraph(_safe(str(r.get("detail", ""))), styles["body"]), # type: ignore
            ])
        col_w = [4.5 * cm, 1.8 * cm, 1.6 * cm, 8.1 * cm]
        ntable = Table(nrows, colWidths=col_w, repeatRows=1)
        ntable.setStyle(_std_table(len(nrows), SECTION_NBC))
        for ri, r in enumerate(nbc_rules, 1):
            if ri >= len(nrows):
                break
            clr = _status_color(r.get("status", "fail"))
            ntable.setStyle(TableStyle([("TEXTCOLOR", (1, ri), (1, ri), clr)]))
        story.append(ntable)
    else:
        story.append(Paragraph("No NBC data available.", styles["body"]))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 6: ENERGY EFFICIENCY
    # ═══════════════════════════════════════════════════════════════════════════
    _section(story, "Energy Efficiency Analysis", "section_teal", styles, SECTION_TEAL)
    story.append(_score_badge(energy_score, energy_grade, styles))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        "Energy efficiency measures how well the design minimizes energy consumption "
        "through passive design, ventilation, and material choices.",
        styles["body"]
    ))
    story.append(Spacer(1, 0.3 * cm))

    energy_rules = energy_result.get("rules", [])
    if energy_rules:
        erows = [["Rule", "Status", "Pts", "Detail"]]
        for r in energy_rules:
            if r.get("max", 0) == 0:
                continue
            erows.append([
                Paragraph(_safe(str(r.get("rule", ""))), styles["body"]), # type: ignore
                _status_cell(r.get("status", "")),
                f"{r.get('points', 0)}/{r.get('max', 0)}",
                Paragraph(_safe(str(r.get("detail", ""))), styles["body"]), # type: ignore
            ])
        col_w = [4.5 * cm, 1.8 * cm, 1.6 * cm, 8.1 * cm]
        etable = Table(erows, colWidths=col_w, repeatRows=1)
        etable.setStyle(_std_table(len(erows), SECTION_TEAL))
        for ri, r in enumerate(energy_rules, 1):
            if ri >= len(erows):
                break
            clr = _status_color(r.get("status", "fail"))
            etable.setStyle(TableStyle([("TEXTCOLOR", (1, ri), (1, ri), clr)]))
        story.append(etable)
    else:
        story.append(Paragraph("No energy data available.", styles["body"]))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 7: SUNLIGHT ANALYSIS
    # ═══════════════════════════════════════════════════════════════════════════
    _section(story, "Sunlight Analysis", "section_sun", styles, SECTION_SUN)
    story.append(_score_badge(sun_score, sun_grade, styles))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        "Sunlight analysis evaluates how much natural daylight each room receives "
        "based on its orientation, window placement, and entry direction.",
        styles["body"]
    ))
    story.append(Spacer(1, 0.3 * cm))

    # Insights bullets
    insights = sunlight_result.get("insights", [])
    if insights:
        story.append(Paragraph("<b>Key Insights:</b>", styles["body_bold"]))
        for insight in insights:
            story.append(Paragraph(f"• {_safe(str(insight))}", styles["insight"]))
        story.append(Spacer(1, 0.3 * cm))

    # Per-window sunlight table
    windows_sun = sunlight_result.get("windows_sunlight", {})
    sun_rules   = sunlight_result.get("rules", [])

    if windows_sun:
        wrows = [["Window / Room", "Direction", "Sunlight Intensity"]]
        for wname, wdata in windows_sun.items():
            intensity = wdata.get("intensity", 0)
            direction = wdata.get("direction", "N/A")
            bar = "█" * int(intensity / 10) if isinstance(intensity, (int, float)) else ""
            wrows.append([_safe(str(wname)), direction, f"{intensity:.0f}%  {bar}"])
        wt = Table(wrows, colWidths=[6 * cm, 4 * cm, 6 * cm])
        wt.setStyle(_std_table(len(wrows), SECTION_SUN))
        story.append(wt)
        story.append(Spacer(1, 0.3 * cm))

    if sun_rules:
        srows = [["Rule", "Status", "Pts", "Detail"]]
        for r in sun_rules:
            if r.get("max", 0) == 0:
                continue
            srows.append([
                Paragraph(_safe(str(r.get("rule", ""))), styles["body"]), # type: ignore
                _status_cell(r.get("status", "")),
                f"{r.get('points', 0)}/{r.get('max', 0)}",
                Paragraph(_safe(str(r.get("detail", ""))), styles["body"]), # type: ignore
            ])
        st = Table(srows, colWidths=[4.5 * cm, 1.8 * cm, 1.6 * cm, 8.1 * cm], repeatRows=1)
        st.setStyle(_std_table(len(srows), SECTION_SUN))
        for ri, r in enumerate(sun_rules, 1):
            if ri >= len(srows):
                break
            clr = _status_color(r.get("status", "fail"))
            st.setStyle(TableStyle([("TEXTCOLOR", (1, ri), (1, ri), clr)]))
        story.append(st)
    elif not windows_sun:
        story.append(Paragraph("No sunlight data available.", styles["body"]))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 8: BILL OF MATERIALS & COST ESTIMATE
    # ═══════════════════════════════════════════════════════════════════════════
    _section(story, "Bill of Materials — Cost Estimate (INR)", "section_blue", styles, BRAND_ACCENT2)
    story.append(Paragraph(
        f"Total Area: <b>{summary.get('total_area_sqft', 0):.0f} sqft</b>  ·  "
        f"Rate: <b>{_inr(summary.get('rate_per_sqft', 0))}/sqft</b>  ·  "
        f"Grand Total: <b>{_inr(summary.get('grand_total', 0))}</b>",
        styles["meta"]
    ))
    story.append(Spacer(1, 0.3 * cm))

    bom_rows = [["Room", "Area\n(sqft)", "D/W", "Material", "Labour", "Total"]]
    for r in bom.get("rooms", []):
        costs = r.get("costs", {})
        bom_rows.append([
            _safe(r.get("name", "")),
            f"{r.get('area_sqft', 0):.0f}",
            f"{r.get('num_doors', 0)}D/{r.get('num_windows', 0)}W",
            _inr(costs.get("material", 0)),
            _inr(costs.get("labour", 0)),
            _inr(costs.get("total", 0)),
        ])
    bom_rows.append([
        "GRAND TOTAL",
        f"{summary.get('total_area_sqft', 0):.0f}", "",
        _inr(summary.get("material_total", 0)),
        _inr(summary.get("labour_total", 0)),
        _inr(summary.get("grand_total", 0)),
    ])

    col_w = [4 * cm, 1.5 * cm, 1.5 * cm, 3 * cm, 2.8 * cm, 3.2 * cm]
    bom_table = Table(bom_rows, colWidths=col_w, repeatRows=1)
    bom_table.setStyle(_std_table(len(bom_rows), BRAND_ACCENT2))
    story.append(bom_table)

    story.append(Spacer(1, 0.6 * cm))
    story.append(Paragraph(
        "Disclaimer: All cost figures are indicative estimates based on 2026 Indian market rates. "
        "Actual costs depend on location, material quality, site conditions, and contractor rates. "
        "Always obtain a formal Bill of Quantities (BOQ) from a licensed architect before construction.",
        styles["disclaimer"]
    ))

    # ── Build PDF ─────────────────────────────────────────────────────────────
    doc.build(story)
    buf.seek(0)
    return buf.read()
